#!/bin/bash

downloaddrupal_version=4

# Dependency check
if ! [ $(which udownload) ] ; then
	echo The downloaddrupal utility needs the udownload utility. Download it from https://raw.githubusercontent.com/danilocgsilva/download_drupal/master/programfiles/downloaddrupal and puts in the /usr/local/bin/.
	exit
fi

# Input check
if [ -z $1 ]; then
    echo Please, provides the first argument to be the drupal directory name.
    exit
fi

# Actions
packfile=drupal-8.3.1.tar.gz
basepackname=$(basename $packfile .tar.gz)

udownload https://ftp.drupal.org/files/projects/$packfile
tar xvzf $packfile
cp $basepackname/sites/default/default.settings.php $basepackname/sites/default/settings.php
mv $basepackname $1
rm $packfile
