#!/bin/bash

# Input check
if [ -z $1 ]; then
    echo Please, provides the first argument to be the drupal directory name.
    exit
fi

# Functions declarations
uget() {
	if which wget > /dev/null 2>&1; then
		wget $1
	elif which curl > /dev/null 2>&1; then
		curl -O $1
	else
		echo Neither wget or curl is installed in the system. I can\'t continue.
		exit
	fi
}

# Actions
packfile=drupal-8.2.7.tar.gz
basepackname=$(basename $packfile .tar.gz)

uget https://ftp.drupal.org/files/projects/$packfile
tar xvzf $packfile
cp $basepackname/sites/default/default.settings.php $basepackname/sites/default/settings.php
mv $basepackname $1
rm $packfile
