#!/bin/bash

downloaddrupal_version=8
downloaddrupal_uri=https://raw.githubusercontent.com/danilocgsilva/download_drupal/master/src/downloaddrupal

downloaddrupal_download() {
	# Dependency check
	if ! which udownload > /dev/null 2>&1 ; then
		if ! which installfromalias > /dev/null 2>&1 ; then
			echo The downloaddrupalbundle utility needs the udownload utility or the install from alias utility.
			echo For udownload, downloads from https://raw.githubusercontent.com/danilocgsilva/download_drupal/master/programfiles/downloaddrupal and puts in the /usr/local/bin/.
			echo For installfromalias, downloads from https://raw.githubusercontent.com/danilocgsilva/install_from_alias/master/src/installfromalias and puts in the /usr/local/bin/.
			exit
		else
			installfromalias programfiles universal_download udownload
		fi
	fi

	# Input check
	if [ -z $1 ]; then
		echo Please, provides the first argument to be the drupal directory name.
		exit
	fi

	# Actions
	last_drupal_version=8.3.4

	if ! [ -z $2 ]; then
		last_drupal_version=$2
	fi


	packfile=drupal-$last_drupal_version.tar.gz
	basepackname=$(basename $packfile .tar.gz)

	udownload https://ftp.drupal.org/files/projects/$packfile
	tar xvzf $packfile
	cp $basepackname/sites/default/default.settings.php $basepackname/sites/default/settings.php
	mv $basepackname $1
	rm $packfile
}
